config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: {registrations: 'registrations'}

  resources :interpreters, only: [:show, :index, :new, :create] do
    resources :bookings do
      resources :reviews, only: [:new, :create, :show]
    end
    resources :language_skills, only: [:new, :create, :destroy]
  end

  resources :deaf_users, only: [:new, :create, :edit, :update] do
    resources :language_skills, only: [:new, :create, :destroy]
  end

  get 'search', to: "interpreters#index"
  get 'design', to: "pages#design"
  get 'dashboard', to: "interpreters#dashboard"
  get 'profile', to: "deaf_users#profile"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/language_skill.rb
class LanguageSkill < ApplicationRecord
  belongs_to :language
  belongs_to :owner, polymorphic: true
  validates :language, uniqueness: { scope: [:owner_type, :owner_id] }
end

app/controllers/language_skills_controller.rb
class LanguageSkillsController < ApplicationController

  def new
    if current_user.is_interpreter?
      @language_skill = LanguageSkill.new
      @interpreter = Interpreter.find(params[:interpreter_id])
      @languages = @interpreter.languages
    else
      @language_skill = LanguageSkill.new
      @deaf_user = DeafUser.find(params[:deaf_user_id])
      @languages = @deaf_user.languages
    end
  end

  def create
    if current_user.is_interpreter?
      @language_skill = LanguageSkill.new(language_skills_params)
      @interpreter = Interpreter.find(params[:interpreter_id])
      @language_skill.owner = @interpreter
      @language = Language.find(params[:language_skill][:language_id])
      if @language_skill.save
        respond_to do |format|
          format.html { redirect_to dashboard_path(@interpreter) }
          format.js  # <-- will render `app/views/reviews/create.js.erb`
        end
      else
        respond_to do |format|
          format.html { redirect_to 'interpreters/dashboard' }
          format.js  # <-- idem
        end
      end
    else
      @language_skill = LanguageSkill.new(language_skills_params)
      @deaf_user = DeafUser.find(params[:deaf_user_id])
      @language_skill.owner = @deaf_user
      @language = Language.find(params[:language_skill][:language_id])
      if @language_skill.save
        respond_to do |format|
          format.html { redirect_to dashboard_path(@deaf_user) }
          format.js  # <-- will render `app/views/reviews/create.js.erb`
        end
      else
        respond_to do |format|
          format.html { redirect_to 'deaf_users/profile' }
          format.js  # <-- idem
        end
      end
    end
  end


  def destroy
    if current_user.is_interpreter?
      @language_skill = LanguageSkill.find(params[:id])
      @interpreter = Interpreter.find(params[:interpreter_id])
      @language_skill.destroy
      respond_to do |format|
        format.html { redirect_to new_interpreter_language_skill_path(@interpreter) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      @language_skill = LanguageSkill.find(params[:id])
      @deaf_user = DeafUser.find(params[:deaf_user_id])
      @language_skill.destroy
      respond_to do |format|
        format.html { redirect_to new_deaf_user_language_skill_path(@deaf_user) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    end
  end


  private

  def language_skills_params
    params.require(:language_skill).permit(:interpreter_id, :deaf_user_id, :language_id)
  end

end

app/helpers/language_skills_helper.rb
module LanguageSkillsHelper
end

app/views/language_skills/_form.html.erb
<div class="text-center padded-div-bottom">
  <% if current_user.is_interpreter? %>
    <%= simple_form_for([@interpreter, @language_skill], remote: true) do |f| %>
    <%= f.input :language_id, collection: Language.all.order('name ASC') %>
    <%= f.button :submit, 'Add Language!', :class => "add_language" %>
    <% end %>
  <% else %>
    <%= simple_form_for([@deaf_user, @language_skill], remote: true) do |f| %>
      <%= f.input :language_id, collection: Language.all.order('name ASC') %>
      <%= f.button :submit, 'Add Language!', :class => "add_language" %>
    <% end %>
  <% end %>
</div>


<!--
<select name="countries" id="countries" style="width:300px;">
      <option value='ad' data-image="images/msdropdown/icons/blank.gif" data-imagecss="flag ad" data-title="Andorra">Andorra</option>
      <option value='ae' data-image="images/msdropdown/icons/blank.gif" data-imagecss="flag ae" data-title="United Arab Emirates">United Arab Emirates</option>
      <option value='af' data-image="images/msdropdown/icons/blank.gif" data-imagecss="flag af" data-title="Afghanistan">Afghanistan</option>
      <option value='ag' data-image="images/msdropdown/icons/blank.gif" data-imagecss="flag ag" data-title="Antigua and Barbuda">Antigua and Barbuda</option>
      <option value='ai' data-image="images/msdropdown/icons/blank.gif" data-imagecss="flag ai" data-title="Anguilla">Anguilla</option>
      <option value='al' data-image="images/msdropdown/icons/blank.gif" data-imagecss="flag al" data-title="Albania">Albania</option>
      <option value='am' data-image="images/msdropdown/icons/blank.gif" data-imagecss="flag am" data-title="Armenia">Armenia</option>
      <option value='an' data-image="images/msdropdown/icons/blank.gif" data-imagecss="flag an" data-title="Netherlands Antilles">Netherlands Antilles</option>
</select>     -->

app/views/language_skills/_show.html.erb
<% if current_user.is_interpreter %>
  <div class="bubble-tag text-center"> <%= language.name %><%= link_to " x", interpreter_language_skill_path(interpreter,language_skill), method: :delete %></div>
<% else %>
    <div class="bubble-tag text-center"> <%= language.name %><%= link_to " x", deaf_user_language_skill_path(deaf_user,language_skill), method: :delete %></div>
<% end %>

app/views/language_skills/create.js.erb
<% if @language_skill.errors.any? %>
$('#new_language_skill').html("<%= j render 'language_skills/form', deaf_user: @deaf_user, interpreter: @interpreter, language_skill: @language_skill %>")
<% else %>
  // Create a paragraph for the new review. But hide it.
  var new_language = $("<%= j render 'language_skills/show', language: @language, deaf_user: @deaf_user, interpreter: @interpreter, language_skill: @language_skill %>").hide();
  // Add it to the DOM, at the end of the existing reviews. It's still hidden.
  $('#languages').append(new_language);
  // Show the new review with an animation!
  new_language.slideDown();
<% end %>

app/views/language_skills/destroy.js.erb
<% if current_user.is_interpreter %>
  <% if @language_skill.errors.any? %>
  $('#new_language_skill').html("<%= j render 'language_skills/form', interpreter: @interpreter, language_skill: @language_skill %>")
  <% else %>
    // Create a paragraph for the new review. But hide it.
     var new_language = $("<div class='bubble-tag text-center'><%= @language.name %></div>").hide();
    // Add it to the DOM, at the end of the existing reviews. It's still hidden.
    $('#new_language').delete(new_language);
    // Show the new review with an animation!
    new_language.slideDown();
  <% end %>
<% else %>
  <% if @language_skill.errors.any? %>
    $('#new_language_skill').html("<%= j render 'language_skills/form', deaf_user: @deaf_user, language_skill: @language_skill %>")
    <% else %>
      // Create a paragraph for the new review. But hide it.
       var new_language = $("<div class='bubble-tag text-center'><%= @language.name %></div>").hide();
      // Add it to the DOM, at the end of the existing reviews. It's still hidden.
      $('#new_language').delete(new_language);
      // Show the new review with an animation!
      new_language.slideDown();
    <% end %>
<%end >

app/views/language_skills/new.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-xs-offset-3">
        <% if current_user.is_interpreter? %>
        <h2>Pick your languages</h2>

        <%= render 'language_skills/form', interpreter: @interpreter, language_skill: @language_skill %>

        <div id="languages" class="margin-bottom-30">
          <% @interpreter.language_skills.each do |language_skill| %>
          <div class="bubble-tag text-center"> <%= language_skill.language.name %><%= link_to " x", interpreter_language_skill_path(@interpreter,language_skill), method: :delete %></div>
          <% end %>
        </div>
        <div class="text-right extra-padded-div">
          <button type="button" class="btn-grey"><%= link_to "Finish", dashboard_path(@interpreter)%></button></div>
          <% else %>
          <h2>Pick your languages</h2>

          <%= render 'language_skills/form', deaf_user: @deaf_user, language_skill: @language_skill %>

          <div id="languages" class="margin-bottom-30">
            <% @deaf_user.language_skills.each do |language_skill| %>
            <div class="bubble-tag text-center"> <%= language_skill.language.name %><%= link_to " x", deaf_user_language_skill_path(@deaf_user,language_skill), method: :delete %></div>
            <% end %>
          </div>
          <div class="text-right extra-padded-div">
            <button type="button" class="btn-grey"><%= link_to "Finish", profile_path(@deaf_user)%></button></div>
            <% end %>
          </div>
        </div>
      </div>

    </div>