config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: {registrations: 'registrations'}

  resources :interpreters, only: [:show, :index, :new, :create] do
    resources :bookings do
      resources :reviews, only: [:new, :create, :show]
    end
    resources :language_skills, only: [:new, :create, :destroy]
  end

  resources :deaf_users, only: [:new, :create, :edit, :update] do
    resources :language_skills, only: [:new, :create, :destroy]
  end

  get 'search', to: "interpreters#index"
  get 'design', to: "pages#design"
  get 'dashboard', to: "interpreters#dashboard"
  get 'profile', to: "deaf_users#profile"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/deaf_user.rb
class DeafUser < ApplicationRecord
  belongs_to :user
  has_many :language_skills, as: :owner
  has_many :languages, through: :language_skills
  has_many :bookings
  has_many :reviews, through: :bookings
  validates :name, presence: :true, uniqueness: :true
  mount_uploader :photo, PhotoUploader
end

app/controllers/deaf_users_controller.rb
class DeafUsersController < ApplicationController

  before_action :find_deaf_user, only: [:edit, :update, :destroy]

  def new
    @deaf_user = DeafUser.new
  end

  def create
    @deaf_user = DeafUser.new(deaf_user_params)
    @deaf_user.user = current_user
    if @deaf_user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @deaf_user.update(deaf_user_params)
    redirect_to interpreters_path
  end

  def destroy
    @deaf_user.destroy
  end

  def profile
    if current_user.is_interpreter
      redirect_to root_path
      # @booking.interpreter = Booking.joins(:interpreter).where("interpreter.id" => @interpreter.name)

    else
      @deaf_user = DeafUser.find_by(user_id: current_user.id)
      @bookings = @deaf_user.bookings
      @past_bookings = []
      @upcoming_bookings = []
      @bookings.each do |booking|
        Time.now > (booking.booking_date + booking.duration) ? @past_bookings << booking : @upcoming_bookings << booking
      end
    end
  end

  private

  def find_deaf_user
    @deaf_user = DeafUser.find(params[:id])
  end

  def deaf_user_params
    params.require(:deaf_user).permit(:name, :location, :photo, :photo_cache, languages:[])
  end

end

app/helpers/deaf_users_helper.rb
module DeafUsersHelper
end

app/views/deaf_users/edit.html.erb
<div class= "text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <h1>Keep your SignKick profile up-to-date!</h1>
        <p>Please update information about yourself:</p>
        <%= simple_form_for [@deaf_user] do |f| %>
        <%= f.input :name, placeholder: "Name",required: true, autofocus: true  %>
        <%= f.input :location, placeholder: "Location" %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/deaf_users/new.html.erb
<div class= "text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <h1>Welcome to SignKick!</h1>
        <h2>We're glad you're here.</h2>
        <h2>We hope to make finding and booking an interpreter as easy as possible.</h2>
        <p>Please give us some more information about yourself:</p>
        <%= simple_form_for [@deaf_user] do |f| %>
        <%= f.input :name, placeholder: "Name",required: true, autofocus: true  %>
        <%= f.input :location, placeholder: "Location" %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit %>
        <% end %>
      </div>
    </div>
  </div>

app/views/deaf_users/profile.html.erb
<div class="container">
  <div class="row">
    <div class="dashboard-container padded-div-top-less">
      <div class="col-xs-12 col-sm-3">
        <%= image_tag @deaf_user.photo, class: "dashboard-profile-pic " %>
        <h1><%= (@deaf_user.name).upcase %></h1>
      </div>
      <div class="col-xs-12 col-sm-3">
        <div class="profile-border">
          <h2>PROFILE</h2>
          <div class="row">
            <div class="col-xs-6">
              <h3>Languages</h3>
              <% @deaf_user.languages.each do |language|%>
              <p><%= language.name %></p>
              <% end %>
              <p class="underline"><%= link_to "Add a Language", new_deaf_user_language_skill_path(@deaf_user)%></p>
            </div>
            <div class="col-xs-6">
              <h3>Location</h3>
              <p><%= @deaf_user.location %></p>
              <p class= "underline"><%= link_to "Edit Profile", edit_deaf_user_path(@deaf_user)%></p>
            </div>
          </div>
        </div>
      </div>
      <div class= "col-xs-12 col-sm-6">
        <div class= "dashboard-upcoming-bookings ">
          <h2>UPCOMING BOOKINGS</h2>
          <div class="row">
            <% @upcoming_bookings.each do |booking| %>
            <div class="col-xs-6">
              <h3>Your booking with <%= booking.interpreter.name %>:</h3>
              <p class="text-left">Date <%=  booking.booking_date.strftime("%d/%m/%Y") %>  </p>
              <p class="text-left">From <%=  booking.booking_date.strftime("%H:%M") %>  to  <%=  (booking.booking_date + booking.duration).strftime("%H:%M") %> </p>
              <p class="text-left">$<%= (booking.interpreter.price.to_f  *  (booking.duration.to_f / 3600)) %></p>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="dashboard-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-3 col-sm-offset-3">
        <h2>
          PAST BOOKINGS
        </h2>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="row">
          <h2>
            REVIEWS YOU'VE WRITTEN
          </h2>
        </div>
      </div>
    </div>
    <% @past_bookings.each do |booking| %>
      <div class="padded-bottom">
      <div class="row">
        <div class="col-xs-12 col-sm-3 col-sm-offset-3">
          <h3>Your booking with <%= booking.interpreter.name %>:</h3>
          <p class="text-left">Date: <%=  booking.booking_date.strftime("%d/%m/%Y") %>  </p>
          <p class="text-left">From: <%=  booking.booking_date.strftime("%H:%M") %>  to  <%=  (booking.booking_date + booking.duration).strftime("%H:%M") %> </p>
          <p class="text-left"><%= booking.interpreter.location %></p>
          <p class="text-left">$<%= (booking.interpreter.price.to_f  *  (booking.duration.to_f / 3600)) %></p>
        </div>
        <div class="col-xs-12 col-sm-4">
          <% if booking.review.nil? %>
          <div class="row">
            <h3>
              How was your experience with <%= link_to booking.interpreter.name, interpreter_path(booking.interpreter) %>?
            </h3>
            <p class="underline">
              <%= link_to "Leave a Review!", new_interpreter_booking_review_path(booking.interpreter ,booking)%>
            </p>
          </div>
          <% else %>
          <div class="row">
            <h3> Overall Performance:
              <span class="gold-star">
                <%= generate_review_stars(booking.review.overall_performance)%>
              </span>
            </h3>
            <div class="row">
              <div class="col-xs-6">
                <p>
                  Language Skill: <%= generate_review_stars(booking.review.language_ability)%>
                </p>
                <p>
                  Friendliness: <%= generate_review_stars(booking.review.friendliness)%>
                </p>
              </div>
              <div class="col-xs-6">
                <p>
                  Professionalism:<%= generate_review_stars(booking.review.professionalism)%>
                </p>
                <p>
                  Punctuality: <%= generate_review_stars(booking.review.punctuality)%>
                </p>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <h3>
                  Description: <span><p><%= booking.review.content%></p></span>
                </h3>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      </div>
      <% end %>

  </div>
</div>