config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: {registrations: 'registrations'}

  resources :interpreters, only: [:show, :index, :new, :create] do
    resources :bookings do
      resources :reviews, only: [:new, :create, :show]
    end
    resources :language_skills, only: [:new, :create, :destroy]
  end

  resources :deaf_users, only: [:new, :create, :edit, :update] do
    resources :language_skills, only: [:new, :create, :destroy]
  end

  get 'search', to: "interpreters#index"
  get 'design', to: "pages#design"
  get 'dashboard', to: "interpreters#dashboard"
  get 'profile', to: "deaf_users#profile"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: url('<%= image_path 'background.jpeg'%>')">
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-xs-offset-3">
          <div class="banner-content">
            <h1>Welcome to SignKick</h1>
            <p>Find your sign language partner</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_booking.html.erb
<div class= "sk-booking-form booking-form">
  <%= form_tag(interpreter_bookings_path(@interpreter)) do %>

  <div class= "label-spacing">
    <%= label_tag(:location, "Location") %>
    <%= text_field_tag(:location) %>
  </div>


  <div class="label-spacing">
    <%= label_tag(:booking_date, "Date") %>
    <%= date_field_tag(:booking_date) %>
  </div>

  <ul>
    <li>
      <%= label_tag(:start_time, "Start time") %>
      <%= time_select(:start_time, "Start time") %>
    </li><li>
    <%= label_tag(:duration, "Duration") %>
    <%= select_tag(:duration, options_for_select(select_duration)) %>
  </li>
</ul>

<!-- Button trigger modal -->
<button type="button" class="book-interpreter-button green-book-interpreter-button full-width" id="book-btn" data-toggle="modal" data-target="#myModal">
  Book
</button>


<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title">Booking confirmation</h2>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to book with <%= @interpreter.name %>?</p>
        <div class="booking-details">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="book-interpreter-button white-book-interpreter-button" data-dismiss="modal">Cancel</button>
        <%= submit_tag 'Confirm',class: "book-interpreter-button green-book-interpreter-button"%>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<% end %>
</div>

app/views/layouts/_card.html.erb
<div class="col-xs-12 col-sm-4">
  <div class="card-container">
   <div class="card">
     <div class="front">
       <div class="cover" style="background-image: url('<%= image_path "#{interpreter.location.downcase}.jpg"%>')">

       </div>
       <div class="user">
         <%= image_tag interpreter.photo , class: "img-circle" %>
       </div>
       <div class="content">
         <div class="main">
           <h3 class="name"><%= interpreter.name %></h3>
           <p class="profession"><%= interpreter.location %></p>
           <p class="gold-star text-center"><%= generate_review_stars(interpreter.overall_performance)%></p>
         </div>
         <div class="footer">
           <div class="rating">
             <i class="fa fa-mail-forward"></i>
           </div>
         </div>
       </div>
     </div> <!-- end front panel -->
     <div class="back">
      <%= link_to interpreter_path(interpreter) do %>
      <div class="header">
       <h5 class="motto"> Access <%=interpreter.name%>'s Profile</h5>
     </div>
     <div class="content">
       <div class="main">
         <h4 class="text-center">Bio</h4>
         <p class="text-center"><%= truncate(interpreter.bio, :length => 180, separator: ' ', :omission => "...." , :escape => false)%></p>
         <div class="stats-container">
           <div class="stats">
            <%if interpreter.years_of_experience.nil? %>
            <h4>Languages</h4>
            <%= list_languages(interpreter) %>
          </div>
          <div class="stats">
           <h4>Location</h4>
           <p>
             <%= intepreter.location %>
             <% else %>
             <h4>Languages</h4>
             <%= list_languages(interpreter) %>
           </div>
           <div class="stats">
             <h4>Experience</h4>
             <p>
               <%= interpreter.years_of_experience %> years
               <% end %>
             </p>
           </div>
         </div>
       </div>
     </div>
     <% end %>
     <div class="footer">
       <div class="social-links text-center">
         <i class="fa fa-envelope-o"></i>
       </div>
     </div>
   </div> <!-- end back panel -->
 </div> <!-- end card -->
</div> <!-- end card-container -->
</div>

app/views/layouts/_flashes.html.erb
  <% if flash[:notice] %>
    <p class="alert alert-success alert-dismissible fade-in" role="alert">
    <%= flash[:notice] %></p>
  <% end %>



  <% if flash[:alert] %>
    <p class="alert alert-danger" role="alert"><%= flash[:alert] %></p>
  <% end %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <ul class="list-inline text-center">

      <li>
        <%= link_to "http://facebook.com", class: "footer-link" do %>
        <i class="fa fa-facebook"></i>
        <% end %>
      </li>

      <li>
        <%= link_to "http://instagram.com", class: "footer-link" do %>
        <i class="fa fa-instagram"></i>
        <% end %>
      </li>

      <li>
        <%= link_to "http://twitter.com", class: "footer-link" do %>
        <i class="fa fa-twitter"></i>
        <% end %>
      </li>
    </ul>

    <div class= "list-inline text-center">
      <p>SignKick Copyright © 2016 </p>

    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-sk-left">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.jpg", width: "100px"%>
    <% end %>
    <% if user_signed_in? %>
    <%= link_to t(".sign_in", default: "Profile"), profile_path, class: "navbar-wagon-item navbar-wagon-link btn-pink btn-dashboard"%>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->

    <!-- Different navigation if login or not -->
  <% if user_signed_in? %>
        <ul>
          <%= link_to "#" do %>
          <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </ul>
        <ul>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </ul>
  <% else %>
  <!-- Login text link -->
  <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link btn-pink sk-btn-login"%>
  <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link btn-sign-up"%>

  <% end %>

  <!-- Button (call-to-action) -->
</div>

<!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li>
          <%= link_to "#" do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
          <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
  </div>

</div>
</div>

app/views/layouts/_sidekick_navbar.html.erb
<div class="navbar-sidekick">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-sidekick-brand" do %>
  <%= image_tag "logo.png", class: "navbar-sidekick-brand" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-sidekick-right hidden-xs hidden-sm">

   <!-- Different navigation if login or not -->
   <% if user_signed_in? %>

   <!-- Notification -->


   <!-- Profile picture and dropdown -->
   <div class="navbar-sidekick-item">
     <div class="dropdown">
     <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-sidekick-menu", "data-toggle" => "dropdown" %>
     <ul class="dropdown-menu dropdown-menu-right navbar-sidekick-dropdown-menu">
         <li>
           <%= link_to "#" do %>
           <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
           <% end %>
         </li>
         <li>
           <%= link_to "#" do %>
           <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
           <% end %>
         </li>
         <li>
           <%= link_to destroy_user_session_path, method: :delete do %>
           <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
           <% end %>
         </li>
       </ul>
     </div>
   </div>

   <% else %>

   <%= link_to "Log in", new_user_session_path, class: "" %>
   <%= link_to "Sign up", new_user_registration_path, class: "sk-btn-login btn-light-green" %>

   <!-- Login text link -->

   <% end %>

   <!-- Button (call-to-action) -->
 </div>

 <!-- Dropdown list appearing on mobile only -->
 <div class="navbar-sidekick-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-sidekick-dropdown-menu">
      <li><a href="#">Some mobile link</a></li>
      <li><a href="#">Other one</a></li>
      <li><a href="#">Other one</a></li>
    </ul>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>SignKick</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= favicon_link_tag 'favicon-signkick.png' %>
</head>
<body>
  <%= render 'layouts/navbar'%>
  <%= render 'layouts/flashes'%>
  <div class="master-container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer'%>
  <%= javascript_include_tag 'application' %>
</body>
</html>